### ISSUE TITLE
feat: mobile roadmap section

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-lp#17]
### Feature Proposal

The roadmap is an image-like style, but for the mobile version, it needs to be shrunk to fit in the vertical screen of the mobile.

### Suggested Proposal

- [x] Make a larger pink square, one that fits the entire mobile screen. One where the text can be fitted in the center.
- [x] Get the texts and fit inside the squares.
- [x] Pile them, but don't fit merge in a single image, because this will allow developers to create other effects on top of it.

### Related Code

The [Figma design](https://www.figma.com/community/file/1335063165996522243)

**Comment by andressa-cabral** [comment]
![image](https://github.com/w3b3d3v/web3task-lp/assets/101841063/ba45759c-dc77-46a7-8746-0ee69d6e1cd8)
✅design created separately so that programmers can create effects
